//
// Academic License - for use in teaching, academic research, and meeting
// course requirements at degree granting institutions only.  Not for
// government, commercial, or other organizational use.
// File: dJ_IK_Geo_p.cpp
//
// MATLAB Coder version            : 3.4
// C/C++ source code generated on  : 17-Jul-2022 20:41:51
//

// Include Files
#include "rt_nonfinite.h"
#include "FK_Geo_p.h"
#include "FK_Geo_v.h"
#include "IK_Geo_p.h"
#include "IK_Geo_v.h"
#include "J_FK_Geo_p.h"
#include "J_IK_Geo_p.h"
#include "dJ_FK_Geo_p.h"
#include "dJ_IK_Geo_p.h"
#include "KinGeo_rtwutil.h"

// Function Definitions

//
// DJ_IK_GEO_P
//     [DJ_QFLEXION,DJ_QKNEE] = DJ_IK_GEO_P(LA,LL,DLA,DLL)
// Arguments    : double LA
//                double LL
//                double dLA
//                double dLL
//                double dJ_qFlexion[2]
//                double dJ_qKnee[2]
// Return Type  : void
//
void dJ_IK_Geo_p(double, double LL, double, double dLL, double dJ_qFlexion[2],
                 double dJ_qKnee[2])
{
  double t2;
  double t4;
  double t5;
  double t6;
  double t7;
  double t8;

  //     This function was generated by the Symbolic Math Toolbox version 8.0.
  //     17-Jul-2022 20:28:13
  t2 = LL * LL;
  t4 = 1.0 / (LL * LL);
  t5 = 1.0 / rt_powd_snf(LL, 3.0);
  t6 = (t2 + 0.030052640000000019) * (t2 + 0.030052640000000019);
  t7 = 1.0 / LL;
  t8 = t4 * t6 * -0.89268931726549694 + 1.0;
  dJ_qFlexion[0] = 0.0;
  dJ_qFlexion[1] = dLL * (1.0 / std::sqrt(t8) * (t7 * 1.8896447467876041 - (t2 +
    0.030052640000000019) * t5 * 1.8896447467876041) + 1.0 / rt_powd_snf(t8, 1.5)
    * ((t2 + 0.030052640000000019) * t4 * 0.944822373393802 - 1.8896447467876041)
    * ((t2 + 0.030052640000000019) * t7 * 3.5707572690619882 - t5 * t6 *
       1.7853786345309941) * 0.5);
  t4 = t2 * 1.8896447467876041;
  t5 = (t4 - 1.0016111866969011) * (t4 - 1.0016111866969011);
  dJ_qKnee[0] = 0.0;
  dJ_qKnee[1] = dLL * (1.0 / std::sqrt(-t5 + 1.0) * 3.7792894935752082 + t2 *
                       (t4 - 1.0016111866969011) / rt_powd_snf(-t5 + 1.0, 1.5) *
                       14.283029076247949);
}

//
// File trailer for dJ_IK_Geo_p.cpp
//
// [EOF]
//
