//
// Academic License - for use in teaching, academic research, and meeting
// course requirements at degree granting institutions only.  Not for
// government, commercial, or other organizational use.
// File: FK_Geo_p.cpp
//
// MATLAB Coder version            : 3.4
// C/C++ source code generated on  : 17-Jul-2022 20:41:51
//

// Include Files
#include "rt_nonfinite.h"
#include "FK_Geo_p.h"
#include "FK_Geo_v.h"
#include "IK_Geo_p.h"
#include "IK_Geo_v.h"
#include "J_FK_Geo_p.h"
#include "J_IK_Geo_p.h"
#include "dJ_FK_Geo_p.h"
#include "dJ_IK_Geo_p.h"

// Function Definitions

//
// FK_GEO_P
//     [LA,LL] = FK_GEO_P(QFLEXION,QKNEE)
// Arguments    : double qFlexion
//                double qKnee
//                double *LA
//                double *LL
// Return Type  : void
//
void FK_Geo_p(double qFlexion, double qKnee, double *LA, double *LL)
{
  double t4;

  //     This function was generated by the Symbolic Math Toolbox version 8.0.
  //     17-Jul-2022 20:28:18
  t4 = std::cos(qKnee + 0.035) * 0.5292;
  *LA = (qFlexion - std::acos(1.0 / std::sqrt(t4 + 0.53005264000000007) * (t4 +
           0.56010528000000015) * 0.944822373393802)) + 0.1;
  *LL = std::sqrt(t4 + 0.53005264000000007);
}

//
// File trailer for FK_Geo_p.cpp
//
// [EOF]
//
